config/routes.rb
Rails.application.routes.draw do

  root 'tokens#index'

  resources :tokens, only: [:index, :new, :create, :show] do
    collection do
      get 'clear_queue'
      get 'request_token'
    end
  end

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :string(255)      not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class Client < ActiveRecord::Base
  # making id column act as primary key
  self.primary_key = :id
  before_create :set_id
  has_many :tokens

  def set_id
    unless id.present?
      self.id = SecureRandom.hex(4) + '-' + SecureRandom.hex(2) + '-' + SecureRandom.hex(2)
    end
  end

end

app/models/token.rb
# == Schema Information
#
# Table name: tokens
#
#  id            :integer          not null, primary key
#  token_type    :integer
#  token_index   :integer
#  message       :text
#  client_id     :string(255)
#  serial_number :string(255)
#  served        :boolean          default(FALSE)
#  created_at    :datetime
#  updated_at    :datetime
#

class Token < ActiveRecord::Base
  belongs_to :client
  enum token_type: [:premium, :standard, :free]
  before_create :assign_token

  validates :token_type, :presence => {message: "Token type is required"}
  validates :client_id, :presence => {message: "Client Id is required"}

  def assign_token
    self.token_index = next_token_index
    self.serial_number = next_serial_number
  end

  private

  def self.base_token token_type
    {premium: 1, standard: 4, free: 9}[token_type.to_sym]
  end

  def next_token_index
    last_token =  Token.where(token_type: Token.token_types[token_type], served: false).order('token_index DESC').first
    if last_token.present?
      Token.next_index(token_type, last_token.token_index)
    else
      Token.base_token token_type
    end
  end

  def self.next_index type, index
    if type == "premium"
      index % 10 == 3 ? index + 8 : index + 1
    elsif type == "standard"
      index % 10 == 8 ? index + 6 : index + 1
    elsif type == "free"
      index % 10 == 0 ? index + 9 : index + 1
    end
  end

  def next_serial_number
    tokenize (self.token_index % 999)
  end

  def tokenize token_index
    'A' + token_index.to_s.rjust(3, '0')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  def index
    if params[:type]
      @export_tokens = Token.where(token_type: Token.token_types[params[:type]], served: false).order('created_at')
    else
      @export_tokens = Token.where(served: false).order('created_at')
    end

    if !params[:message].nil?
      @export_tokens = @export_tokens.where("lower(message) LIKE ? ", "%"+params[:message].downcase()+"%")
    end

    @tokens = @export_tokens.page(params[:page]).per(100)
    respond_to do |format|
      format.html {}
      format.json {render json: @tokens}
    end
  end

  def new
    @token = Token.new
  end

  def show
    @token = Token.find(params[:id])
    respond_to do |format|
      format.html {}
      format.json {render json: @token}
    end
  end

  def create
    @token = Token.new(token_params)
    respond_to do |format|
      if @token.save
        format.html { redirect_to tokens_path, notice: 'Token was successfully created.' }
        format.json { render json: @token, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  def request_token
    begin
      @token = Token.new(params.permit(:token_type, :message, :client_id))
      if @token.save
        render json: @token, status: :ok
      else
        render json: {message: @token.errors}, status: 400
      end
    rescue StandardError => e
      render json: {message: e.message}, status: 400
    end
  end

  def clear_queue
    if Token.update_all(served: true)
      render json: {message: "Queue Successfully Cleared"}
    else
      render json: {message: "Some error occured while trying to clear the queue"}
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def token_params
    params.require(:token).permit(:token_type, :message, :client_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hate2waitBackend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tokens/_form.html.erb
<%= form_for @token do |f| %>
  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :message %>
    <%= f.text_field :message %>
  </div>
  <br>
  <div>
    <%= f.label :client_id %>
    <%= f.text_field :client_id %>
  </div>
  <br>
  <div>
    <%= f.label :token_type %>
    <%= f.select :token_type, options_for_select([["Premium", "premium"], ["Standard", "standard"], ["Free", "free"]]), "data-placeholder"=> "Select Token Type" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokens/index.html.erb
<h1>Listing tokens </h1>

<h2>Total Tokens in Queue: <%=@export_tokens.count%></h2>

<form action="" method="get" style="margin-bottom: 30px;">
    Message:
    <input class="form-control"  value="<%= params[:message] %>" name="message" type="text" placeholder="Enter Message">
    <button type="submit">Filter</button>
    <%= link_to 'Clear', '?' %>
</form>

<div><%= link_to 'New Token', new_token_path %></div>
<div><%= link_to 'Clear Queue', clear_queue_tokens_path %></div>
<br>
<div style="float: right"><%= paginate @tokens %></div>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <tr>
    <td><b>ID</b></td>
    <td><b>Token Type</b></td>
    <td><b>Serial Number</b></td>
    <td><b>Created At</b></td>
    <td><b>Message</b></td>
  </tr>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= link_to token.id, token_path(token) %></td>
        <td><%= token.token_type %></td>
        <td><%= token.serial_number %></td>
        <td><%= token.created_at %></td>
        <td><%= token.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div style="float: right"><%= paginate @tokens %></div>

app/views/tokens/new.html.erb
<h1>New token</h1>

<%= render 'form' %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>
<p>id: <%= @token.id %></p>
<p>client_id: <%= @token.client_id %></p>
<p>message: <%= @token.message %></p>
<p>token_type: <%= @token.token_type %></p>
<%= link_to 'Back', tokens_path %>